//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileSRC.MobileRemote.Properties
{
    using System;
    using System.Reflection;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    Assembly assembly = null;
                    if (Platform.IsVGA)
                    {
                        assembly = Assembly.LoadFrom(@"MobileRemote.Resources.VGA.dll");
                    }
                    else
                    {
                        assembly = Assembly.LoadFrom(@"MobileRemote.Resources.QVGA.dll");
                    }
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobileSRC.MobileRemote.Properties.Resources", assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        internal static System.Drawing.Bitmap arrow_0
        {
            get
            {
                object obj = ResourceManager.GetObject("arrow_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap arrow_1
        {
            get
            {
                object obj = ResourceManager.GetObject("arrow_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap arrow_2
        {
            get
            {
                object obj = ResourceManager.GetObject("arrow_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap arrow_3
        {
            get
            {
                object obj = ResourceManager.GetObject("arrow_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap arrow_off
        {
            get
            {
                object obj = ResourceManager.GetObject("arrow_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap arrow_on
        {
            get
            {
                object obj = ResourceManager.GetObject("arrow_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Back
        {
            get
            {
                object obj = ResourceManager.GetObject("Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap backspace
        {
            get
            {
                object obj = ResourceManager.GetObject("backspace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap button_down
        {
            get
            {
                object obj = ResourceManager.GetObject("button_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap button_push
        {
            get
            {
                object obj = ResourceManager.GetObject("button_push", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap button_up
        {
            get
            {
                object obj = ResourceManager.GetObject("button_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap closebutton
        {
            get
            {
                object obj = ResourceManager.GetObject("closebutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap closebuttondown
        {
            get
            {
                object obj = ResourceManager.GetObject("closebuttondown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap connected
        {
            get
            {
                object obj = ResourceManager.GetObject("connected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap connected_down
        {
            get
            {
                object obj = ResourceManager.GetObject("connected_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Custom_Button_Down
        {
            get
            {
                object obj = ResourceManager.GetObject("Custom_Button_Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Custom_Button_Set
        {
            get
            {
                object obj = ResourceManager.GetObject("Custom_Button_Set", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Custom_Button_Up
        {
            get
            {
                object obj = ResourceManager.GetObject("Custom_Button_Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Custom_MouseButton_Down
        {
            get
            {
                object obj = ResourceManager.GetObject("Custom_MouseButton_Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Custom_MouseButton_Set
        {
            get
            {
                object obj = ResourceManager.GetObject("Custom_MouseButton_Set", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Custom_MouseButton_Up
        {
            get
            {
                object obj = ResourceManager.GetObject("Custom_MouseButton_Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap delete
        {
            get
            {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap disconnected
        {
            get
            {
                object obj = ResourceManager.GetObject("disconnected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap disconnected_down
        {
            get
            {
                object obj = ResourceManager.GetObject("disconnected_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap down
        {
            get
            {
                object obj = ResourceManager.GetObject("down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap enter
        {
            get
            {
                object obj = ResourceManager.GetObject("enter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap escape
        {
            get
            {
                object obj = ResourceManager.GetObject("escape", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Forward
        {
            get
            {
                object obj = ResourceManager.GetObject("Forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap inputs
        {
            get
            {
                object obj = ResourceManager.GetObject("inputs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap inputs_down
        {
            get
            {
                object obj = ResourceManager.GetObject("inputs_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap key
        {
            get
            {
                object obj = ResourceManager.GetObject("key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap keyboard
        {
            get
            {
                object obj = ResourceManager.GetObject("keyboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap keyboard_down
        {
            get
            {
                object obj = ResourceManager.GetObject("keyboard_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap keyboard_sel
        {
            get
            {
                object obj = ResourceManager.GetObject("keyboard_sel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap keydown
        {
            get
            {
                object obj = ResourceManager.GetObject("keydown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap keyset
        {
            get
            {
                object obj = ResourceManager.GetObject("keyset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap kget
        {
            get
            {
                object obj = ResourceManager.GetObject("kget", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap left
        {
            get
            {
                object obj = ResourceManager.GetObject("left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap media
        {
            get
            {
                object obj = ResourceManager.GetObject("media", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap media_down
        {
            get
            {
                object obj = ResourceManager.GetObject("media_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap media_sel
        {
            get
            {
                object obj = ResourceManager.GetObject("media_sel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap mediacircle_down
        {
            get
            {
                object obj = ResourceManager.GetObject("mediacircle_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap mediacircle_down_off
        {
            get
            {
                object obj = ResourceManager.GetObject("mediacircle_down_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap mediacircle_next
        {
            get
            {
                object obj = ResourceManager.GetObject("mediacircle_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap mediacircle_next_off
        {
            get
            {
                object obj = ResourceManager.GetObject("mediacircle_next_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap mediacircle_prev
        {
            get
            {
                object obj = ResourceManager.GetObject("mediacircle_prev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap mediacircle_prev_off
        {
            get
            {
                object obj = ResourceManager.GetObject("mediacircle_prev_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap mediacircle_up
        {
            get
            {
                object obj = ResourceManager.GetObject("mediacircle_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap mediacircle_up_off
        {
            get
            {
                object obj = ResourceManager.GetObject("mediacircle_up_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap mediaorb
        {
            get
            {
                object obj = ResourceManager.GetObject("mediaorb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap mediaorb_off
        {
            get
            {
                object obj = ResourceManager.GetObject("mediaorb_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap menu_down
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap menu_expand
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap menu_up
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap mobileremote_splash
        {
            get
            {
                object obj = ResourceManager.GetObject("mobileremote_splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap mouse
        {
            get
            {
                object obj = ResourceManager.GetObject("mouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap mouse_down
        {
            get
            {
                object obj = ResourceManager.GetObject("mouse_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap mouse_sel
        {
            get
            {
                object obj = ResourceManager.GetObject("mouse_sel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Mute
        {
            get
            {
                object obj = ResourceManager.GetObject("Mute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap okbutton
        {
            get
            {
                object obj = ResourceManager.GetObject("okbutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap okbuttondown
        {
            get
            {
                object obj = ResourceManager.GetObject("okbuttondown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap orb_off
        {
            get
            {
                object obj = ResourceManager.GetObject("orb_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap orb_on
        {
            get
            {
                object obj = ResourceManager.GetObject("orb_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap PlayPause
        {
            get
            {
                object obj = ResourceManager.GetObject("PlayPause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap powerpoint
        {
            get
            {
                object obj = ResourceManager.GetObject("powerpoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap powerpoint_off
        {
            get
            {
                object obj = ResourceManager.GetObject("powerpoint_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap present
        {
            get
            {
                object obj = ResourceManager.GetObject("present", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap present_down
        {
            get
            {
                object obj = ResourceManager.GetObject("present_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap present_sel
        {
            get
            {
                object obj = ResourceManager.GetObject("present_sel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap right
        {
            get
            {
                object obj = ResourceManager.GetObject("right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap settings
        {
            get
            {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap settings_down
        {
            get
            {
                object obj = ResourceManager.GetObject("settings_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap settings_sel
        {
            get
            {
                object obj = ResourceManager.GetObject("settings_sel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap shift
        {
            get
            {
                object obj = ResourceManager.GetObject("shift", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap space
        {
            get
            {
                object obj = ResourceManager.GetObject("space", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Stop
        {
            get
            {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap tab
        {
            get
            {
                object obj = ResourceManager.GetObject("tab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap titlebar
        {
            get
            {
                object obj = ResourceManager.GetObject("titlebar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap titlebarcornerleft
        {
            get
            {
                object obj = ResourceManager.GetObject("titlebarcornerleft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap titlebarcornerright
        {
            get
            {
                object obj = ResourceManager.GetObject("titlebarcornerright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap touch
        {
            get
            {
                object obj = ResourceManager.GetObject("touch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap touch_down
        {
            get
            {
                object obj = ResourceManager.GetObject("touch_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap touch_sel
        {
            get
            {
                object obj = ResourceManager.GetObject("touch_sel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap touchpanel
        {
            get
            {
                object obj = ResourceManager.GetObject("touchpanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap up
        {
            get
            {
                object obj = ResourceManager.GetObject("up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap VolumeDown
        {
            get
            {
                object obj = ResourceManager.GetObject("VolumeDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap VolumeUp
        {
            get
            {
                object obj = ResourceManager.GetObject("VolumeUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap waitingorb_0
        {
            get
            {
                object obj = ResourceManager.GetObject("waitingorb_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap waitingorb_1
        {
            get
            {
                object obj = ResourceManager.GetObject("waitingorb_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap waitingorb_2
        {
            get
            {
                object obj = ResourceManager.GetObject("waitingorb_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap waitingorb_3
        {
            get
            {
                object obj = ResourceManager.GetObject("waitingorb_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap windows
        {
            get
            {
                object obj = ResourceManager.GetObject("windows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
